// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slqmtywrcktxkiqqldnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNscW10eXdyY2t0eGtpcXFsZG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzI5MjgsImV4cCI6MjA2MjkwODkyOH0.T-g6sEMGYz7_xLJeiXe3tiYRWpVN0jkjglpje9MyAes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);